### ISSUE TITLE
HTML Blocking

### ISSUE THREAD

**Issue by ZSchuler** [ZSchuler/ZSchuler.github.io#7]
Create the foundations of the website using HTML and some basic CSS. This should only be the basics with titles and placeholder text. There needs to be the home section, which should take up the entirety of the screen, and below it sections for About Me, Projects, Education, and Contact. These don't need to take up the entirety of the screen.

**Comment by DhanunjayRam** [comment]
<html>
<head>
<meta charset="UFT-8">
<meta name="viewport" width="device-width">
<link rel="stylesheet" href="style.css">
</head>
<body>
<section id="home">
<h1> welcome to my website</h2>
<p> content </p>
</section>
<section id= "about me">
<h1> about you"</h1>
</section>
<section id="projects">
<h1>"projects"</h1>
<p>"content"</p>
</section>
<section id="education">
<h1> "education"</h1>
<p>"content</p>
<section>
<section id="contact">
<h1>contact</h1>
<p> "content</p>
</section>
</body>
</html>
